(function(){
  'use strict';
  const cfg=window.SITE_CONFIG||{};
  const msg=(id,text)=>{const e=document.getElementById(id);if(e)e.textContent=text||''};
  if(!window.supabase?.createClient){msg('loginMsg','Não foi possível carregar o serviço de autenticação.');return;}
  if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.startsWith('COLE_')||!cfg.SUPABASE_ANON_KEY||cfg.SUPABASE_ANON_KEY.startsWith('COLE_')){msg('loginMsg','Configure assets/site-config.js antes de usar o painel.');return;}
  const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY); const emailEl=document.getElementById('email'); const passwordEl=document.getElementById('password');
  const loginView=document.getElementById('loginView'),appView=document.getElementById('appView');
  document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg('loginMsg','Entrando...');const {error}=await sb.auth.signInWithPassword({email:emailEl.value.trim(),password:passwordEl.value});if(error)msg('loginMsg','Não foi possível entrar. Confira e-mail e senha.');else await boot();});
  document.getElementById('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
  document.getElementById('photoInput').addEventListener('change',uploadFiles);
  document.getElementById('saveTextBtn').onclick=saveTexts;
  async function boot(){const {data:{user}}=await sb.auth.getUser();if(!user){loginView.hidden=false;appView.hidden=true;return;}loginView.hidden=true;appView.hidden=false;await Promise.all([loadPhotos(),loadTexts()]);}
  async function loadPhotos(){const {data,error}=await sb.from('photos').select('*').order('sort_order',{ascending:true});if(error){msg('uploadMsg','Erro ao carregar fotos.');return}const list=document.getElementById('photosList');list.replaceChildren();for(const p of data||[]){const {data:signed}=await sb.storage.from('site-photos').createSignedUrl(p.storage_path,3600);const card=document.createElement('article');card.className='photo';card.innerHTML='';const img=document.createElement('img');img.src=signed?.signedUrl||'';img.alt=p.alt_text||p.title||'';card.appendChild(img);const body=document.createElement('div');body.className='photo-body';const status=document.createElement('div');status.className='status';status.textContent=p.published?'PUBLICADA':'RASCUNHO';body.appendChild(status);const title=document.createElement('input');title.value=p.title||'';title.placeholder='Título da foto';const alt=document.createElement('input');alt.value=p.alt_text||'';alt.placeholder='Descrição acessível (alt)';body.append(title,alt);const row=document.createElement('div');row.className='row';const save=document.createElement('button');save.textContent='Salvar';save.onclick=()=>updatePhoto(p.id,{title:title.value.trim(),alt_text:alt.value.trim()});const pub=document.createElement('button');pub.className=p.published?'muted':'';pub.textContent=p.published?'Despublicar':'Publicar';pub.onclick=()=>updatePhoto(p.id,{published:!p.published});const up=document.createElement('button');up.className='muted';up.textContent='↑';up.onclick=()=>movePhoto(p,-1,data);const down=document.createElement('button');down.className='muted';down.textContent='↓';down.onclick=()=>movePhoto(p,1,data);const del=document.createElement('button');del.className='danger';del.textContent='Excluir';del.onclick=()=>deletePhoto(p);row.append(save,pub,up,down,del);body.appendChild(row);card.appendChild(body);list.appendChild(card)}}
  async function uploadFiles(e){const files=[...e.target.files];e.target.value='';if(!files.length)return;for(const file of files){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>10*1024*1024){msg('uploadMsg','Aceitamos JPG, PNG ou WebP de até 10 MB.');continue}msg('uploadMsg',`Enviando ${file.name}...`);const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('site-photos').upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error){msg('uploadMsg','Falha no upload: '+error.message);continue}const {count}=await sb.from('photos').select('id',{count:'exact',head:true});const {error:dbError}=await sb.from('photos').insert({storage_path:path,title:file.name.replace(/\.[^.]+$/,''),alt_text:file.name.replace(/\.[^.]+$/,''),sort_order:(count||0)+1,published:false});if(dbError){await sb.storage.from('site-photos').remove([path]);msg('uploadMsg','A foto foi enviada, mas não pôde ser cadastrada.');continue}}msg('uploadMsg','Upload concluído. Novas fotos entram como rascunho.');await loadPhotos()}
  async function updatePhoto(id,patch){const {error}=await sb.from('photos').update(patch).eq('id',id);if(error)msg('uploadMsg','Não foi possível salvar.');else await loadPhotos()}
  async function deletePhoto(p){if(!confirm('Excluir esta foto definitivamente?'))return;const {error:se}=await sb.storage.from('site-photos').remove([p.storage_path]);if(se){msg('uploadMsg','Não foi possível remover o arquivo.');return}const {error}=await sb.from('photos').delete().eq('id',p.id);if(error)msg('uploadMsg','Arquivo removido, mas o cadastro precisa ser verificado.');else await loadPhotos()}
  async function movePhoto(p,dir,all){const i=all.findIndex(x=>x.id===p.id),j=i+dir;if(j<0||j>=all.length)return;const a=all[i],b=all[j];const {error}=await sb.from('photos').update({sort_order:b.sort_order}).eq('id',a.id);if(error)return;await sb.from('photos').update({sort_order:a.sort_order}).eq('id',b.id);await loadPhotos()}
  async function loadTexts(){const {data}=await sb.from('site_content').select('key,value');const map=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));document.querySelectorAll('[data-key]').forEach(el=>{el.value=map[el.dataset.key]||''})}
  async function saveTexts(){const payload=[...document.querySelectorAll('[data-key]')].map(el=>({key:el.dataset.key,value:el.value}));const {error}=await sb.from('site_content').upsert(payload);msg('textMsg',error?'Não foi possível salvar os textos.':'Textos salvos.');}
  sb.auth.getSession().then(boot);
})();
